-- ============================================================
-- RMRP Помощник 2.0 — миграция БД
-- Выполнять в Supabase SQL Editor ПОСЛЕ rmrp_database.sql и release_migration.sql.
-- Скрипт идемпотентен: его можно запускать повторно.
-- ============================================================

-- 1. «В сети» для админ-панели --------------------------------
alter table public.profiles add column if not exists last_seen_at timestamptz;

-- 2. Главы и порядок статей + быстрый поиск ---------------------
alter table public.law_articles add column if not exists chapter text;
alter table public.law_articles add column if not exists position integer;
create index if not exists idx_law_articles_law_pos on public.law_articles(law_id, position);

create extension if not exists pg_trgm;
create index if not exists idx_law_articles_content_trgm on public.law_articles using gin (content gin_trgm_ops);
create index if not exists idx_law_articles_title_trgm   on public.law_articles using gin (title gin_trgm_ops);

-- 3. Последнее изученное ---------------------------------------
create table if not exists public.article_views (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  law_article_id bigint not null references public.law_articles(id) on delete cascade,
  viewed_at timestamptz not null default now(),
  unique (user_id, law_article_id)
);
alter table public.article_views enable row level security;
drop policy if exists "article_views_own" on public.article_views;
create policy "article_views_own" on public.article_views for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
create index if not exists idx_article_views_user_time on public.article_views(user_id, viewed_at desc);

-- 4. Избранные тесты -------------------------------------------
create table if not exists public.test_favorites (
  user_id uuid not null references public.profiles(id) on delete cascade,
  test_id bigint not null references public.tests(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, test_id)
);
alter table public.test_favorites enable row level security;
drop policy if exists "test_favorites_own" on public.test_favorites;
create policy "test_favorites_own" on public.test_favorites for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- 5. Статистика законов (глав / статей) для карточек ------------
create or replace view public.law_stats with (security_invoker = true) as
  select law_id, count(*)::int as articles, count(distinct chapter)::int as chapters
  from public.law_articles group by law_id;
grant select on public.law_stats to anon, authenticated;

-- 6. Гостевой режим: чтение справочных данных без входа ---------
-- Только публичные тексты законов, объявления и тесты. Профили, история и результаты остаются закрытыми.
drop policy if exists "laws_read_guest" on public.laws;
create policy "laws_read_guest" on public.laws for select to anon using (is_active);
drop policy if exists "articles_read_guest" on public.law_articles;
create policy "articles_read_guest" on public.law_articles for select to anon using (true);
drop policy if exists "versions_read_guest" on public.law_versions;
create policy "versions_read_guest" on public.law_versions for select to anon using (true);
drop policy if exists "announcements_read_guest" on public.announcements;
create policy "announcements_read_guest" on public.announcements for select to anon
  using (is_active and (expires_at is null or expires_at > now()));
drop policy if exists "tests_read_guest" on public.tests;
create policy "tests_read_guest" on public.tests for select to anon using (is_active);
drop policy if exists "questions_read_guest" on public.questions;
create policy "questions_read_guest" on public.questions for select to anon using (true);

-- 7. Вход по имени пользователя ---------------------------------
-- ВНИМАНИЕ: функция отдаёт email по логину неавторизованному клиенту (нужно, чтобы вход работал по имени).
-- Если не хотите раскрывать email по логину — удалите функцию: вход останется только по email.
create or replace function public.login_email(p_username text)
returns text
language sql
stable
security definer
set search_path = public, auth
as $$
  select u.email::text
  from auth.users u
  join public.profiles p on p.id = u.id
  where lower(p.username) = lower(p_username)
    and p.status = 'ACTIVE'
  limit 1;
$$;
revoke all on function public.login_email(text) from public;
grant execute on function public.login_email(text) to anon, authenticated;

-- 8. Общие настройки --------------------------------------------
insert into public.app_settings (key, value) values ('discord_app_id', '')
on conflict (key) do nothing;
insert into public.app_settings (key, value) values ('app_version', '2.0.0')
on conflict (key) do update set value = excluded.value, updated_at = now();
