-- RMRP Помощник: профиль + безопасный скример.
-- Выполнить после rmrp_database.sql / release_migration.sql.

alter table public.profiles
  add column if not exists bio text not null default '';

create table if not exists public.prank_events (
  id bigint generated by default as identity primary key,
  target_user_id uuid not null references public.profiles(id) on delete cascade,
  created_by uuid not null references public.profiles(id) on delete cascade,
  kind text not null default 'screamer',
  created_at timestamptz not null default now(),
  consumed_at timestamptz null
);

alter table public.prank_events enable row level security;

drop policy if exists "prank_founder_insert" on public.prank_events;
create policy "prank_founder_insert" on public.prank_events
for insert to authenticated
with check (public.is_founder() and created_by = auth.uid());

drop policy if exists "prank_target_read" on public.prank_events;
create policy "prank_target_read" on public.prank_events
for select to authenticated
using (target_user_id = auth.uid() or public.is_founder());

drop policy if exists "prank_target_consume" on public.prank_events;
create policy "prank_target_consume" on public.prank_events
for update to authenticated
using (target_user_id = auth.uid() or public.is_founder())
with check (target_user_id = auth.uid() or public.is_founder());

create index if not exists idx_prank_events_target_pending
on public.prank_events(target_user_id, consumed_at, created_at);
