-- ============================================================
-- RMRP ПОМОЩНИК by Kinzec X WOLF
-- Supabase / PostgreSQL schema
-- Версия: 1.0
-- ============================================================

create extension if not exists "pgcrypto";

-- ------------------------------------------------------------
-- 1. ENUM-типы
-- ------------------------------------------------------------

do $$ begin
  create type public.user_role as enum ('FOUNDER','ADMIN','MODERATOR','PREMIUM','USER');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.user_status as enum ('ACTIVE','BLOCKED','BANNED');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.test_difficulty as enum ('EASY','MEDIUM','HARD');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.report_status as enum ('NEW','IN_PROGRESS','RESOLVED','REJECTED');
exception when duplicate_object then null;
end $$;

-- ------------------------------------------------------------
-- 2. PROFILES
-- Пользователь Supabase Auth -> профиль приложения
-- Пароли здесь НЕ хранятся.
-- ------------------------------------------------------------

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text,
  avatar_url text,
  role public.user_role not null default 'USER',
  premium boolean not null default false,
  status public.user_status not null default 'ACTIVE',
  allow_pranks boolean not null default false,
  created_at timestamptz not null default now(),
  last_login timestamptz,
  updated_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 3. ЗАКОНОДАТЕЛЬСТВО
-- ------------------------------------------------------------

create table if not exists public.laws (
  id bigint generated by default as identity primary key,
  name text not null,
  short_name text,
  law_number text,
  description text,
  source_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.law_articles (
  id bigint generated by default as identity primary key,
  law_id bigint not null references public.laws(id) on delete cascade,
  article_number text not null,
  title text,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(law_id, article_number)
);

create table if not exists public.law_versions (
  id bigint generated by default as identity primary key,
  law_id bigint not null references public.laws(id) on delete cascade,
  version text not null,
  change_description text,
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 4. ТЕСТЫ
-- ------------------------------------------------------------

create table if not exists public.tests (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  description text,
  difficulty public.test_difficulty not null default 'MEDIUM',
  question_count integer not null default 0 check (question_count >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  test_id bigint not null references public.tests(id) on delete cascade,
  question text not null,
  answer_a text not null,
  answer_b text not null,
  answer_c text not null,
  answer_d text not null,
  correct_answer char(1) not null check (correct_answer in ('A','B','C','D')),
  explanation text,
  difficulty public.test_difficulty not null default 'MEDIUM',
  created_at timestamptz not null default now()
);

create table if not exists public.test_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  test_id bigint not null references public.tests(id) on delete cascade,
  score integer not null default 0,
  total_questions integer not null default 0,
  correct_answers integer not null default 0,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.test_answers (
  id bigint generated by default as identity primary key,
  result_id bigint not null references public.test_results(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete cascade,
  selected_answer char(1) not null check (selected_answer in ('A','B','C','D')),
  is_correct boolean not null default false
);

-- ------------------------------------------------------------
-- 5. ИЗБРАННОЕ / ИСТОРИЯ / ИИ
-- ------------------------------------------------------------

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  law_article_id bigint not null references public.law_articles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(user_id, law_article_id)
);

create table if not exists public.search_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  query text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  question text not null,
  answer text,
  law_article_id bigint references public.law_articles(id) on delete set null,
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 6. ОБЪЯВЛЕНИЯ
-- ------------------------------------------------------------

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  type text not null default 'INFO',
  is_active boolean not null default true,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  expires_at timestamptz
);

-- ------------------------------------------------------------
-- 7. МОДЕРАЦИЯ
-- ------------------------------------------------------------

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.profiles(id) on delete cascade,
  target_user_id uuid references public.profiles(id) on delete set null,
  reason text not null,
  description text,
  status public.report_status not null default 'NEW',
  assigned_to uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.moderation_actions (
  id bigint generated by default as identity primary key,
  moderator_id uuid references public.profiles(id) on delete set null,
  target_user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  reason text,
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 8. ЖУРНАЛ АДМИНИСТРАТОРА
-- ------------------------------------------------------------

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  target_type text,
  target_id text,
  details jsonb,
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 9. НАСТРОЙКИ ПРИЛОЖЕНИЯ
-- ------------------------------------------------------------

create table if not exists public.app_settings (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value text,
  updated_at timestamptz not null default now()
);

insert into public.app_settings (key, value)
values
  ('maintenance_mode', 'false'),
  ('registration_enabled', 'true'),
  ('ai_enabled', 'true'),
  ('pranks_enabled', 'true')
on conflict (key) do nothing;

-- ------------------------------------------------------------
-- 10. ПОЛЬЗОВАТЕЛЬСКИЕ ФУНКЦИИ
-- ------------------------------------------------------------

create or replace function public.is_admin_or_founder()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role in ('FOUNDER','ADMIN')
      and status = 'ACTIVE'
  );
$$;

create or replace function public.is_moderator_or_higher()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role in ('FOUNDER','ADMIN','MODERATOR')
      and status = 'ACTIVE'
  );
$$;

create or replace function public.is_founder()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'FOUNDER'
      and status = 'ACTIVE'
  );
$$;

-- ------------------------------------------------------------
-- 11. Создание профиля после регистрации Auth
-- ------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  generated_username text;
begin
  generated_username :=
    coalesce(
      nullif(new.raw_user_meta_data->>'username', ''),
      split_part(coalesce(new.email, 'user'), '@', 1)
    );

  insert into public.profiles (id, username, display_name)
  values (
    new.id,
    generated_username,
    coalesce(new.raw_user_meta_data->>'display_name', generated_username)
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- ------------------------------------------------------------
-- 12. updated_at
-- ------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

drop trigger if exists laws_updated_at on public.laws;
create trigger laws_updated_at
before update on public.laws
for each row execute procedure public.set_updated_at();

drop trigger if exists articles_updated_at on public.law_articles;
create trigger articles_updated_at
before update on public.law_articles
for each row execute procedure public.set_updated_at();

drop trigger if exists tests_updated_at on public.tests;
create trigger tests_updated_at
before update on public.tests
for each row execute procedure public.set_updated_at();

-- ------------------------------------------------------------
-- 13. RLS
-- ------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.laws enable row level security;
alter table public.law_articles enable row level security;
alter table public.law_versions enable row level security;
alter table public.tests enable row level security;
alter table public.questions enable row level security;
alter table public.test_results enable row level security;
alter table public.test_answers enable row level security;
alter table public.favorites enable row level security;
alter table public.search_history enable row level security;
alter table public.ai_history enable row level security;
alter table public.announcements enable row level security;
alter table public.reports enable row level security;
alter table public.moderation_actions enable row level security;
alter table public.audit_logs enable row level security;
alter table public.app_settings enable row level security;

-- ------------------------------------------------------------
-- 14. Политики PROFILES
-- ------------------------------------------------------------

drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin"
on public.profiles for select
to authenticated
using (
  id = auth.uid() or public.is_admin_or_founder()
);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (
  id = auth.uid()
);

drop policy if exists "profiles_admin_update" on public.profiles;
create policy "profiles_admin_update"
on public.profiles for update
to authenticated
using (public.is_admin_or_founder())
with check (public.is_admin_or_founder());

-- ------------------------------------------------------------
-- 15. Законы: читать могут авторизованные пользователи
-- Изменять — админы/основатель
-- ------------------------------------------------------------

drop policy if exists "laws_read_authenticated" on public.laws;
create policy "laws_read_authenticated"
on public.laws for select
to authenticated
using (true);

drop policy if exists "laws_admin_write" on public.laws;
create policy "laws_admin_write"
on public.laws for all
to authenticated
using (public.is_admin_or_founder())
with check (public.is_admin_or_founder());

drop policy if exists "articles_read_authenticated" on public.law_articles;
create policy "articles_read_authenticated"
on public.law_articles for select
to authenticated
using (true);

drop policy if exists "articles_admin_write" on public.law_articles;
create policy "articles_admin_write"
on public.law_articles for all
to authenticated
using (public.is_admin_or_founder())
with check (public.is_admin_or_founder());

drop policy if exists "versions_read_authenticated" on public.law_versions;
create policy "versions_read_authenticated"
on public.law_versions for select
to authenticated
using (true);

drop policy if exists "versions_admin_write" on public.law_versions;
create policy "versions_admin_write"
on public.law_versions for all
to authenticated
using (public.is_admin_or_founder())
with check (public.is_admin_or_founder());

-- ------------------------------------------------------------
-- 16. Тесты
-- ------------------------------------------------------------

drop policy if exists "tests_read_authenticated" on public.tests;
create policy "tests_read_authenticated"
on public.tests for select
to authenticated
using (true);

drop policy if exists "tests_admin_write" on public.tests;
create policy "tests_admin_write"
on public.tests for all
to authenticated
using (public.is_admin_or_founder())
with check (public.is_admin_or_founder());

drop policy if exists "questions_read_authenticated" on public.questions;
create policy "questions_read_authenticated"
on public.questions for select
to authenticated
using (true);

drop policy if exists "questions_admin_write" on public.questions;
create policy "questions_admin_write"
on public.questions for all
to authenticated
using (public.is_admin_or_founder())
with check (public.is_admin_or_founder());

-- ------------------------------------------------------------
-- 17. Результаты тестов
-- ------------------------------------------------------------

drop policy if exists "results_own" on public.test_results;
create policy "results_own"
on public.test_results for select
to authenticated
using (user_id = auth.uid() or public.is_admin_or_founder());

drop policy if exists "results_insert_own" on public.test_results;
create policy "results_insert_own"
on public.test_results for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "answers_own" on public.test_answers;
create policy "answers_own"
on public.test_answers for select
to authenticated
using (
  exists (
    select 1 from public.test_results r
    where r.id = result_id
      and (r.user_id = auth.uid() or public.is_admin_or_founder())
  )
);

drop policy if exists "answers_insert_own" on public.test_answers;
create policy "answers_insert_own"
on public.test_answers for insert
to authenticated
with check (
  exists (
    select 1 from public.test_results r
    where r.id = result_id
      and r.user_id = auth.uid()
  )
);

-- ------------------------------------------------------------
-- 18. Избранное / поиск / ИИ
-- ------------------------------------------------------------

drop policy if exists "favorites_own" on public.favorites;
create policy "favorites_own"
on public.favorites for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "search_history_own" on public.search_history;
create policy "search_history_own"
on public.search_history for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "ai_history_own" on public.ai_history;
create policy "ai_history_own"
on public.ai_history for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

-- ------------------------------------------------------------
-- 19. Объявления
-- ------------------------------------------------------------

drop policy if exists "announcements_read" on public.announcements;
create policy "announcements_read"
on public.announcements for select
to authenticated
using (is_active = true or public.is_admin_or_founder());

drop policy if exists "announcements_admin" on public.announcements;
create policy "announcements_admin"
on public.announcements for all
to authenticated
using (public.is_admin_or_founder())
with check (public.is_admin_or_founder());

-- ------------------------------------------------------------
-- 20. Жалобы
-- ------------------------------------------------------------

drop policy if exists "reports_create_own" on public.reports;
create policy "reports_create_own"
on public.reports for insert
to authenticated
with check (author_id = auth.uid());

drop policy if exists "reports_read_own_or_mod" on public.reports;
create policy "reports_read_own_or_mod"
on public.reports for select
to authenticated
using (
  author_id = auth.uid()
  or public.is_moderator_or_higher()
);

drop policy if exists "reports_mod_update" on public.reports;
create policy "reports_mod_update"
on public.reports for update
to authenticated
using (public.is_moderator_or_higher())
with check (public.is_moderator_or_higher());

-- ------------------------------------------------------------
-- 21. Модерация и аудит
-- ------------------------------------------------------------

drop policy if exists "moderation_mod_read" on public.moderation_actions;
create policy "moderation_mod_read"
on public.moderation_actions for select
to authenticated
using (public.is_moderator_or_higher());

drop policy if exists "moderation_mod_insert" on public.moderation_actions;
create policy "moderation_mod_insert"
on public.moderation_actions for insert
to authenticated
with check (public.is_moderator_or_higher());

drop policy if exists "audit_admin_read" on public.audit_logs;
create policy "audit_admin_read"
on public.audit_logs for select
to authenticated
using (public.is_admin_or_founder());

drop policy if exists "audit_admin_insert" on public.audit_logs;
create policy "audit_admin_insert"
on public.audit_logs for insert
to authenticated
with check (public.is_admin_or_founder());

-- ------------------------------------------------------------
-- 22. Настройки приложения
-- ------------------------------------------------------------

drop policy if exists "settings_read_authenticated" on public.app_settings;
create policy "settings_read_authenticated"
on public.app_settings for select
to authenticated
using (true);

drop policy if exists "settings_admin_write" on public.app_settings;
create policy "settings_admin_write"
on public.app_settings for all
to authenticated
using (public.is_admin_or_founder())
with check (public.is_admin_or_founder());

-- ------------------------------------------------------------
-- 23. Индексы
-- ------------------------------------------------------------

create index if not exists idx_profiles_role on public.profiles(role);
create index if not exists idx_profiles_status on public.profiles(status);
create index if not exists idx_law_articles_law_id on public.law_articles(law_id);
create index if not exists idx_questions_test_id on public.questions(test_id);
create index if not exists idx_results_user_id on public.test_results(user_id);
create index if not exists idx_results_test_id on public.test_results(test_id);
create index if not exists idx_ai_history_user_id on public.ai_history(user_id);
create index if not exists idx_search_history_user_id on public.search_history(user_id);
create index if not exists idx_audit_logs_user_id on public.audit_logs(user_id);

-- ============================================================
-- ГОТОВО
-- После регистрации первого аккаунта:
--
-- 1) Открой Table Editor -> profiles
-- 2) Найди свой аккаунт
-- 3) Временно/первый раз можно выполнить:
--
-- update public.profiles
-- set role = 'FOUNDER', premium = true
-- where username = 'ТВОЙ_USERNAME';
--
-- ВАЖНО: делать это только для своего первого аккаунта.
-- ============================================================
